version: '3.8'
services:

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - mqtt_network

  humac:
    build: ./
    container_name: v2Gateway
    privileged: true
    volumes:
      - ./config:/humac/config
    restart: always
    depends_on:
      - mosquitto 
    networks:
      - mqtt_network

volumes:
  mosquitto_data:
  mosquitto_logs:

networks:
  mqtt_network:
    driver: bridge
