[
    ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=85, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=0, Name='Objects'), DisplayName=LocalizedText(Locale=None, Text='Objects'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=61, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)),
    ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=86, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=0, Name='Types'), DisplayName=LocalizedText(Locale=None, Text='Types'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=61, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)), 
    ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=87, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=0, Name='Views'), DisplayName=LocalizedText(Locale=None, Text='Views'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=61, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0))
    ]


[ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35,NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=2253, NamespaceIndex=0, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=0, Name='Server'), DisplayName=LocalizedText(Locale=None, Text='Server'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=2004, NamespaceIndex=0, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0)), 
 ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=23470, NamespaceIndex=0, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=0, Name='Aliases'), DisplayName=LocalizedText(Locale=None, Text='Aliases'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=23456, NamespaceIndex=0, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0)),
 ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=31915, NamespaceIndex=0, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=0, Name='Locations'), DisplayName=LocalizedText(Locale=None, Text='Locations'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=61, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)),
 ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier='85/0:Simulation', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Simulation'), DisplayName=LocalizedText(Locale=None, Text='Simulation'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=61, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)), 
 ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier='StaticData', NamespaceIndex=5, NodeIdType=<NodeIdType.String: 3>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=5, Name='StaticData'), DisplayName=LocalizedText(Locale=None, Text='StaticData'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=61, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)), 
 ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier='MyObjectsFolder', NamespaceIndex=6, NodeIdType=<NodeIdType.String: 3>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=6, Name='MyObjects'), DisplayName=LocalizedText(Locale=None, Text='MyObjects'), NodeClass_=<NodeClass.Object: 1>, TypeDefinition=ExpandedNodeId(Identifier=61, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0))]  

[ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=1001, NamespaceIndex=3, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Counter'), DisplayName=LocalizedText(Locale=None, Text='Counter'), NodeClass_=<NodeClass.Variable: 2>, TypeDefinition=ExpandedNodeId(Identifier=63, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)), 
ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=1002, NamespaceIndex=3, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Random'), DisplayName=LocalizedText(Locale=None, Text='Random'), NodeClass_=<NodeClass.Variable: 2>, TypeDefinition=ExpandedNodeId(Identifier=63, NamespaceIndex=0, NodedType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)),
ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=1003, NamespaceIndex=3, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Sawtooth'), DisplayName=LocalizedText(Locale=None, Text='Sawtooth'), NodeClass_=<NodeClass.Variable: 2>, TypeDefinition=ExpandedNodeId(Identifier=63, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)),
ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=1004, NamespaceIndex=3, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Sinusoid'), DisplayName=LocalizedText(Locale=None, Text='Sinusoid'), NodeClass_=<NodeClass.Variable: 2>, ypeDefinition=ExpandedNodeId(Identifier=63, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)), 
ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=1005, NamespaceIndex=3, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Square'), DisplayName=LocalizedText(Locale=None, Text='Square'), NodeClass_=<NodeClass.Variable: 2>, TypeDefinition=ExpandedNodeId(Identifier=63, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)),
ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=1006, NamespaceIndex=3, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Triangle'), DisplayName=LocalizedText(Locale=None, Text='Triangle'), NodeClass_=<NodeClass.Variable: 2>, TypeDefinition=ExpandedNodeId(Identifier=63, NamespaceIndex=0, NodIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0)), 
ReferenceDescription(ReferenceTypeId=NodeId(Identifier=35, NamespaceIndex=0, NodeIdType=<NodeIdType.TwoByte: 0>), IsForward=True, NodeId=ExpandedNodeId(Identifier=1007, NamespaceIndex=3, NodeIdType=<NodeIdType.FourByte: 1>, NamespaceUri=None, ServerIndex=0), BrowseName=QualifiedName(NamespaceIndex=3, Name='Constant'), DisplayName=LocalizedText(Locale=None, Text='Constant'), NodeClass_=<NodeClass.Variable: 2>, TypeDefinition=ExpandedNodeId(Identifier=63, NamespaceIndex=0, odeIdType=<NodeIdType.TwoByte: 0>, NamespaceUri=None, ServerIndex=0))]